exports.seed = function(knex, Promise) {
  return Promise.all([
    knex('users').insert(
      { first_name: 'Ravi',
        last_name: 'Vora',
        email: 'ravivora@email.com',
        password: '1234',
        bio: 'Floofs puggo you are doin me a concern shooberino, pupperino you are doing me a frighten doge, shibe big ol. Heckin good boys blep extremely cuuuuuute fluffer long doggo adorable doggo, dat tungg tho very taste wow very jealous pupper ur givin me a spook woofer, big ol pupper long bois snoot heck. Long woofer blep the neighborhood pupper blop smol borking doggo with a long snoot for pats shooberino, heckin angery woofer borkf borkdrive. Heckin angery woofer big ol pupper shoober ruff boof very taste wow, most angery pupper I have ever seen very jealous pupper bork woofer.',
        profile_image: '/images/ravi-vora-avatar.jpg',
        website_url: 'http://www.ravivora.com/',
        instagram_url: 'https://www.instagram.com/ravivora/',
        facebook_url: 'null',
        twitter_url: 'https://twitter.com/RaviVora',
        location: 'Los Angeles',
        user_type_id: 1
      }),
    knex('users').insert(
      { first_name: 'Olya',
        last_name: 'Kobruseva',
        email: 'olyakobruseva@email.com',
        password: '1234',
        bio: 'Floofs puggo you are doin me a concern shooberino, pupperino you are doing me a frighten doge, shibe big ol. Heckin good boys blep extremely cuuuuuute fluffer long doggo adorable doggo, dat tungg tho very taste wow very jealous pupper ur givin me a spook woofer, big ol pupper long bois snoot heck. Long woofer blep the neighborhood pupper blop smol borking doggo with a long snoot for pats shooberino, heckin angery woofer borkf borkdrive. Heckin angery woofer big ol pupper shoober ruff boof very taste wow, most angery pupper I have ever seen very jealous pupper bork woofer.',
        profile_image: '/images/olya-kobruseva-avatar.jpg',
        website_url: 'http://kobruseva.com/',
        instagram_url: 'https://www.instagram.com/leeloothefirst/',
        facebook_url: 'https://www.facebook.com/LeelooTheFirst',
        twitter_url: 'null',
        location: 'Barcelona',
        user_type_id: 1
      }),
    knex('users').insert(
      { first_name: 'Tim',
        last_name: 'Flach',
        email: 'timflach@email.com',
        password: '1234',
        bio: 'Floofs puggo you are doin me a concern shooberino, pupperino you are doing me a frighten doge, shibe big ol. Heckin good boys blep extremely cuuuuuute fluffer long doggo adorable doggo, dat tungg tho very taste wow very jealous pupper ur givin me a spook woofer, big ol pupper long bois snoot heck. Long woofer blep the neighborhood pupper blop smol borking doggo with a long snoot for pats shooberino, heckin angery woofer borkf borkdrive. Heckin angery woofer big ol pupper shoober ruff boof very taste wow, most angery pupper I have ever seen very jealous pupper bork woofer.',
        profile_image: '/images/tim-flach-avatar.jpg',
        website_url: 'https://timflach.com/',
        instagram_url: 'https://www.instagram.com/timflachphotography/',
        facebook_url: 'https://www.facebook.com/timflachphoto/',
        twitter_url: 'https://twitter.com/TimFlach',
        location: 'London',
        user_type_id: 1
      }),
    knex('users').insert(
      { first_name: 'Lucie',
        last_name: 'Urban',
        email: 'lucyurban@email.com',
        password: '1234',
        bio: 'Floofs puggo you are doin me a concern shooberino, pupperino you are doing me a frighten doge, shibe big ol. Heckin good boys blep extremely cuuuuuute fluffer long doggo adorable doggo, dat tungg tho very taste wow very jealous pupper ur givin me a spook woofer, big ol pupper long bois snoot heck. Long woofer blep the neighborhood pupper blop smol borking doggo with a long snoot for pats shooberino, heckin angery woofer borkf borkdrive. Heckin angery woofer big ol pupper shoober ruff boof very taste wow, most angery pupper I have ever seen very jealous pupper bork woofer.',
        profile_image: '/images/lucy-urban-avatar.jpg',
        website_url: 'http://lucieurban.cz/',
        instagram_url: 'https://www.instagram.com/urban_photographe/',
        facebook_url: 'https://www.facebook.com/URBANPHOTOGRAPHE',
        twitter_url: 'null',
        location: 'Prague',
        user_type_id: 1
      }),
    knex('users').insert(
      { first_name: 'Jenn',
        last_name: 'Repp',
        email: 'jennrepp@email.com',
        password: '1234',
        bio: 'Floofs puggo you are doin me a concern shooberino, pupperino you are doing me a frighten doge, shibe big ol. Heckin good boys blep extremely cuuuuuute fluffer long doggo adorable doggo, dat tungg tho very taste wow very jealous pupper ur givin me a spook woofer, big ol pupper long bois snoot heck. Long woofer blep the neighborhood pupper blop smol borking doggo with a long snoot for pats shooberino, heckin angery woofer borkf borkdrive. Heckin angery woofer big ol pupper shoober ruff boof very taste wow, most angery pupper I have ever seen very jealous pupper bork woofer.',
        profile_image: '/images/jenn-repp-avatar.jpg',
        website_url: 'http://www.jennrepp.com/',
        instagram_url: 'https://www.instagram.com/jennreppphoto/',
        facebook_url: 'http://www.facebook.com/photo.jennrepp',
        twitter_url: 'https://twitter.com/jennreppPhoto',
        location: 'Seattle',
        user_type_id: 1
      }),
    knex('users').insert(
      { first_name: 'Michael',
        last_name: 'Wilson',
        email: 'mwilson@email.com',
        password: '1234',
        bio: 'Floofs puggo you are doin me a concern shooberino, pupperino you are doing me a frighten doge, shibe big ol. Heckin good boys blep extremely cuuuuuute fluffer long doggo adorable doggo, dat tungg tho very taste wow very jealous pupper ur givin me a spook woofer, big ol pupper long bois snoot heck. Long woofer blep the neighborhood pupper blop smol borking doggo with a long snoot for pats shooberino, heckin angery woofer borkf borkdrive. Heckin angery woofer big ol pupper shoober ruff boof very taste wow, most angery pupper I have ever seen very jealous pupper bork woofer.',
        profile_image: '/images/michael-avatar.jpg',
        website_url: 'null',
        instagram_url: 'null',
        facebook_url: 'null',
        twitter_url: 'null',
        location: 'null',
        user_type_id: 2
      }),
    knex('users').insert(
      { first_name: 'Carey',
        last_name: 'Brown',
        email: 'careybrown@email.com',
        password: '1234',
        bio: 'Floofs puggo you are doin me a concern shooberino, pupperino you are doing me a frighten doge, shibe big ol. Heckin good boys blep extremely cuuuuuute fluffer long doggo adorable doggo, dat tungg tho very taste wow very jealous pupper ur givin me a spook woofer, big ol pupper long bois snoot heck. Long woofer blep the neighborhood pupper blop smol borking doggo with a long snoot for pats shooberino, heckin angery woofer borkf borkdrive. Heckin angery woofer big ol pupper shoober ruff boof very taste wow, most angery pupper I have ever seen very jealous pupper bork woofer.',
        profile_image: '/images/carey-avatar.jpg',
        website_url: 'null',
        instagram_url: 'null',
        facebook_url: 'null',
        twitter_url: 'null',
        location: 'null',
        user_type_id: 2
      }),
    knex('users').insert(
      { first_name: 'Rondell',
        last_name: 'Staton',
        email: 'rrrondell@email.com',
        password: '1234',
        bio: 'Floofs puggo you are doin me a concern shooberino, pupperino you are doing me a frighten doge, shibe big ol. Heckin good boys blep extremely cuuuuuute fluffer long doggo adorable doggo, dat tungg tho very taste wow very jealous pupper ur givin me a spook woofer, big ol pupper long bois snoot heck. Long woofer blep the neighborhood pupper blop smol borking doggo with a long snoot for pats shooberino, heckin angery woofer borkf borkdrive. Heckin angery woofer big ol pupper shoober ruff boof very taste wow, most angery pupper I have ever seen very jealous pupper bork woofer.',
        profile_image: '/images/rondell-avatar.jpg',
        website_url: 'null',
        instagram_url: 'null',
        facebook_url: 'null',
        twitter_url: 'null',
        location: 'null',
        user_type_id: 2
      })
  ]);
};